export const HABILIDADES_BLIND_GM = new Set([
  "buscar", "disfrazarse", "documentacion", "imponerse", "manipulacion",
  "ocultar", "percatarse", "perspicacia", "rastrear", "sigilo"
]);

// Habilidades que pueden topar a otras (clave habilidad → claves de sus posibles topes)
export const TOPES_HABILIDAD = {
  armasPunhal: ["montar", "nadar"],
  armasEspada: ["montar", "nadar"],
  armasAsta: ["montar", "nadar"],
  armasMangos: ["montar", "nadar"],
  pelea: ["montar", "nadar"],
  escudo: ["montar", "nadar"],
  arco: ["montar", "nadar"],
  ballesta: ["montar", "nadar"],
  canonDeMano: ["montar", "nadar"],
  honda: ["montar", "nadar"],
  lanzar: ["montar", "nadar"],
  atletismo: ["nadar"],
  trepar: ["nadar"],
  sigilo: ["nadar"],
  hurtar: ["nadar"],
  buscar: ["naturaleza"],
  actuacion:    ["idioma2", "idioma3"],
  callejeo:     ["idioma2", "idioma3"],
  disfrazarse:  ["idioma2", "idioma3"],
  encanto:      ["idioma2", "idioma3"],
  imponerse:    ["idioma2", "idioma3"],
  instruir:     ["idioma2", "idioma3"],
  manipulacion: ["idioma2", "idioma3"],
  memorizar:    ["idioma2", "idioma3"],
  oratoria:     ["idioma2", "idioma3"],
  tratarAnimales: ["idioma2", "idioma3"],
};

// Mapa de clave de arma → nombre que se usa como clave en system.habilidades de un PNJ
export const ARMA_A_HABILIDAD_PNJ = {
  "armasPunhal": "Armas CC - Puñal",
  "armasEspada": "Armas CC - Espada",
  "armasAsta": "Armas CC - Asta",
  "armasMangos": "Armas CC - Mango",
  "pelea": "Pelea",
  "escudo": "Escudo",
  "arco": "Arco",
  "ballesta": "Ballesta",
  "canonDeMano": "Cañón de Mano",
  "honda": "Honda",
  "lanzar": "Lanzar",
};

export const HABILIDADES_OPCIONES = [
  { clave: "academia", label: "Academia" },
  { clave: "actuacion", label: "Actuación" },
  { clave: "arco", label: "Arco" },
  { clave: "armasAsta", label: "Armas de Asta" },
  { clave: "armasEspada", label: "Armas de Espada" },
  { clave: "armasMangos", label: "Armas de Mango" },
  { clave: "armasPunhal", label: "Armas de Puñal" },
  { clave: "artesania", label: "Artesanía" },
  { clave: "atletismo", label: "Atletismo" },
  { clave: "ballesta", label: "Ballesta" },
  { clave: "buscar", label: "Buscar" },
  { clave: "callejeo", label: "Callejeo" },
  { clave: "canonDeMano", label: "Cañón de Mano" },
  { clave: "conocimientoMagico", label: "Conocimiento Mágico" },
  { clave: "disfrazarse", label: "Disfrazarse" },
  { clave: "documentacion", label: "Documentación" },
  { clave: "encanto", label: "Encanto" },
  { clave: "escudo", label: "Escudo" },
  { clave: "esquivar", label: "Esquivar" },
  { clave: "estrategia", label: "Estrategia" },
  { clave: "forzarCerraduras", label: "Forzar Cerraduras" },
  { clave: "honda", label: "Honda" },
  { clave: "hurtar", label: "Hurtar" },
  { clave: "idioma1", label: "Idioma 1 (nativo)" },
  { clave: "idioma2", label: "Idioma 2" },
  { clave: "idioma3", label: "Idioma 3" },
  { clave: "imponerse", label: "Imponerse" },
  { clave: "instruir", label: "Instruir" },
  { clave: "juego", label: "Juego" },
  { clave: "lanzar", label: "Lanzar" },
  { clave: "leyendas", label: "Leyendas" },
  { clave: "manejarBotes", label: "Manejar Botes" },
  { clave: "manejarCarros", label: "Manejar Carros" },
  { clave: "manipulacion", label: "Manipulación" },
  { clave: "medicina", label: "Medicina" },
  { clave: "memorizar", label: "Memorizar" },
  { clave: "montar", label: "Montar" },
  { clave: "multiverso", label: "Multiverso" },
  { clave: "nadar", label: "Nadar" },
  { clave: "naturaleza", label: "Naturaleza" },
  { clave: "navegacion", label: "Navegación" },
  { clave: "ocultar", label: "Ocultar" },
  { clave: "oratoria", label: "Oratoria" },
  { clave: "percatarse", label: "Percatarse" },
  { clave: "pelea", label: "Pelea" },
  { clave: "perspicacia", label: "Perspicacia" },
  { clave: "pociones", label: "Pociones" },
  { clave: "primerosAuxilios", label: "Primeros Auxilios" },
  { clave: "rastrear", label: "Rastrear" },
  { clave: "seguir", label: "Seguir" },
  { clave: "sigilo", label: "Sigilo" },
  { clave: "sueños", label: "Sueños" },
  { clave: "tierrasQuebradas", label: "Tierras Quebradas" },
  { clave: "tratarAnimales", label: "Tratar Animales" },
  { clave: "trepar", label: "Trepar" }
];
